---
title: "lancet-europe"
author: "Reed Garvin"
date: '2022-07-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## loading text



```{r}
library(quanteda)
library(readtext)

# Read text files
raw_docs <- readtext("/Users/reedgarvin/Documents/Hertie/DSL/annual_reports_txt/*.txt", 
                     encoding = "UTF-8")


# Preprocessing with quanteda and create a dfm object
key_corpus <- corpus(raw_docs, text_field = "text")

# If you use the covariate model, please consider using `docvars` argument
key_corpus <- corpus(raw_docs, text_field = "text")

# You can conduct a variety of preprocessing in this step as shown in the next section
key_token <- tokens(key_corpus)

# Create a document-feature matrix (a dfm object) from a token object
key_dfm <- dfm(key_token)
```

## preprocessing



```{r, echo=FALSE}
library(keyATM)
library(quanteda)
library(magrittr)
data(key_corpus)
key_corpus

data_tokens <- tokens(key_corpus,
                      remove_numbers = TRUE, 
                      remove_punct = TRUE, 
                      remove_symbols = TRUE,
                      remove_separators = TRUE,
                      remove_url = TRUE) %>%
                 tokens_tolower() %>%
                 tokens_remove(c(stopwords("english"), 
                               "annual", "report")) %>%
                 tokens_select(min_nchar = 3)
```
## create matrix
```{r}

data_dfm <- dfm(data_tokens) %>%
              dfm_trim(min_termfreq = 5, min_docfreq = 2)
```
## use atm read
```{r}
keyATM_docs <- keyATM_read(texts = data_dfm)
summary(keyATM_docs)
```
## preparing keywords
```{r}
keywords <- list(Health = c("malaria", "diarrhoea", "infection", "disease", "diseases", "sars", "measles", "pneumonia", "epidemic", "epidemics", "pandemic", "pandemics", "epidemiology", "healthcare", "health", "mortality", "morbidity", "nutrition", "illness", "illnesses", "ncd", "ncds", "air_pollution", "nutrition", "malnutrition", "malnourishment", "mental_disorder", "mental_disorders", "stunting"),
                 Co_benefit = c("health_benefit*","win-win", "double_dividend*", "benefit*","cobenefit*", "co-benefit*", "secondary_benefit*", "ancillary_benefit*", "side_benefit*", "collateral_benefit*", "associated_benefit*", "ancillary_effect*", "ancillary_impact*", "side_effect*",  "co-control", "carbon_benefit*", "reduction_benefit*", "synergy", "side_effect*", "spillover", "trade-off*", "distributional_aspect*", "distributional_effect*", "mortality_impact*", "conflict_impact*", "social stability",  "air_pollution", "air_quality", "health*"),
                 Climate_Change = c("climate_change", "changing_climate", "climate_emergency", "climate_crisis", "climate_decay", "global_warming", "green_house", "temperature", "extreme_weather", "global_environmental_change", "climate_variability", "greenhouse", "greenhouse-gas", "low_carbon", "ghge", "ghges", "renewable_energy", "carbon_emission", "carbon_emissions", "carbon_dioxide", "carbon-dioxide", "co2_emission", "co2_emissions", "climate_pollutant", "climate_pollutants", "decarbonization", "decarbonisation", "carbon_neutral", "carbon-neutral", "carbon_neutrality", "climate_neutrality", "climate_action", "net-zero", "net_zero", "global_heating", "heat", "drought", "flood", "wildfire", "food_insecurity"))
                
```
##vis
```{r}
key_viz <- visualize_keywords(docs = keyATM_docs, keywords = keywords)
key_viz
save_fig(key_viz, "keyword.pdf", width = 6.5, height = 4)
```
#Model
```{r}
out <- keyATM(docs              = keyATM_docs,    # text input
              no_keyword_topics = 5,              # number of topics without keywords
              keywords          = keywords,       # keywords
              model             = "base",         # select the model
              options           = list(seed = 250))
save(out, file = "SAVENAME.rds")
#load model
#out <- readRDS(file = "SAVENAME.rds") 
```
#interpreting Results
```{r}
top_words(out)
top_docs(out)
out$theta  # Document-topic distribution
out$phi    # Topic-word distribution
fig_modelfit <- plot_modelfit(out)
fig_modelfit
save_fig(fig_modelfit, "figures/base_modelfit.pdf", width = 7, height = 5)
plot_alpha(out)
save_fig(plot_alpha, "figures/plot_alpha.pdf", width = 7, height = 5)
plot_pi(out)
ave_fig(plot_pi, "figures/plot_pi.pdf", width = 7, height = 5)
```
#distances
```{r}
```